### ISSUE TITLE
Training on Wikipedia is not memory Efficient

### ISSUE THREAD

**Issue by shyamupa** [seomoz/word2gauss#14]
I downloaded a wikipedia dump and extracted raw text from it using Matt Mahoney's [perl script](https://github.com/facebookresearch/fastText/blob/master/wikifil.pl). When I ran the code using the example described in the README.md, the process consumed enormous amounts of memory (>100G).

What am I doing wrong? Or is there something wrong with the code?

**Comment by matt-peters** [comment]
How many words do you have in your vocabulary and what is your embedding dimension?  If you are using diagonal covariance matrices the total memory used is approx. `8 * N * K` where N=number of words, K=embedding dimension.

**Comment by shyamupa** [comment]
I found that the problem was the entire file had only 1 line (the perl script removed all newlines). 

The code in readme operates on a line by line basis, which meant the code was trying to load all of wikipedia into memory for training.
After fixing this, it works.
