### ISSUE TITLE
Entailment experiments not working as original paper

### ISSUE THREAD

**Issue by shyamupa** [seomoz/word2gauss#15]
Hi,

I am trying to use the model for doing word entailment (eg. dog --> mammal) as described in the original paper (Section 6.2). I got the data for the experiment from [this](http://clic.cimec.unitn.it/Files/PublicData/eacl2012-data.zip) link.

However, I cannot reproduce the results for the experiment in the paper. Has anyone tried this and succeeded?

**Comment by matt-peters** [comment]
I haven't tried to reproduce those results.  Are you following the same hyperparameter choices/setup?  What F1 values are you getting?

**Comment by shyamupa** [comment]
I ask the author and tried using the following parameters

```
l2 norm  <100
variance between 0.25 and 1000.0
margin of 5.0
50 dimension
diagonal covariance 
training with IP objective
min-freq for vocab 100
```

trained on wikipedia.
Strangely, I cannot beat the baseline of always predicting `True` (which gets a F1 of 66%).

**Comment by matt-peters** [comment]
Agree that's strange.  As I said I haven't tried to reproduce those results so unfortunately won't be of much help.
